#Page d'accueil Billetterie
mdl_billetterie_view:
    path:    /
    defaults:
        _controller: MdLBilletterieBundle:SelectBillet:index

mdl_billetterie_cmd:
    path:    /commande/{id}
    defaults:
        _controller: MdLBilletterieBundle:SelectBillet:commande
    requirements:
            id: \d+

mdl_billetterie_paiement:
    path:    /paiement/{id}
    defaults:
        _controller: MdLBilletterieBundle:SelectBillet:paiement
    requirements:
            id: \d+