# src/MdL/BilletterieBundle/Resources/config/services.yml

services:
    mdl_billetterie.calculprix:
        class: MdL\BilletterieBundle\CalculPrix\MdLCalculPrix

    mdl_billetterie.refcommande:
            class: MdL\BilletterieBundle\RefCommande\MdLRefCommande

    mdl_billetterie.ctrlnbbillet:
            class: MdL\BilletterieBundle\CtrlNbBillet\MdLCtrlNbBillet
