# src/MdL/BilletterieBundle/Resources/config/services.yml

services:
    mdl_billetterie.calculprix:
        class: MdL\BilletterieBundle\CalculPrix\MdLCalculPrix

    mdl_billetterie.refcommande:
            class: MdL\BilletterieBundle\RefCommande\MdLRefCommande

    mdl_billetterie.ctrlnbbillet:
            class: MdL\BilletterieBundle\CtrlNbBillet\MdLCtrlNbBillet
            arguments: ["@doctrine.orm.entity_manager"]

    mdl_billetterie.enregpmt:
            class: MdL\BilletterieBundle\EnregPmt\MdLEnregPmt