# src/MdL/BilletterieBundle/Resources/config/services.yml

services:
    mdl_billetterie.calculprix:
        class: MdL\BilletterieBundle\CalculPrix\MdLCalculPrix

    mdl_billetterie.refCommande:
            class: MdL\BilletterieBundle\RefCommande\MdLRefCommande
